// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> en = {
  "saiahatynyzdy_tek_bizben_birge_zertteniz": "Explore your journey only with us",
  "sizdin_atynyz": "Your name",
  "email": "Email",
  "password": "Password",
  "qupia_sozdi_rastanyz": "Confirm your password",
  "rastay": "Confirmation",
  "barlyq_oristerdi_toltyry_qajet": "It is necessary to fill in all fields",
  "qupia_sozder_birdei_emes": "Passwords don't match",
  "google_account": "Google account",
  "sizde_eseptik_jazba_bar_ma_munda_juiege_kiriniz": "Do you have an account? Log in here",
  "qupia_sozdi_umyttynyz_ba": "Forgot your password?",
  "durys_elektrondyq_poshta_mekenjaiyn_engiziniz": "Enter the correct email address",
  "elektrondyq_poshta_mekenjaiynyzga_elektrondyq_hat_jiberildi": "The email has been sent to your email address",
  "elektrondyq_poshta": "Email",
  "qazir_qalpyna_keltiriniz": "Restore Now",
  "aya_raiy_boljamy": "Weather \nforecast",
  "ornalasqan_jeriniz": "Your location",
  "jarnama": "Advertisement",
  "qala_tarihy": "History of the city",
  "qazirgi_almaty_aymagynda_arheologtar": "Based on the ancient monuments found by archaeologists on the territory of modern Almaty, we can say that this area has long been inhabited by nomadic and semi-settled tribes. The most unusual monuments of the Saks are the VI—III centuries BC.",
  "orta_gasyrlar": "Middle Ages",
  "vernyi": "Vernyi",
  "kenes_kezeni": "Soviet period",
  "vernyi_qazirgi_almaty": "Verniy (now Almaty) is a city, a military fortress created by the Russian Government on February 4 (February 16), 1854. Soon it grew and turned into a large Cossack village, where settlers from the central regions of Russia (Voronezh, Orel, Kursk provinces) actively came. In 1867, Verniy became the center of the Zhetysu region.",
  "jyly_vernyida": "In 1918, Soviet power was established in Verny. With the region, the city became part of the Turkestan Autonomy within the RSFSR. On February 5 , 1921, it was decided to rename Verny to Almaty after the old name of the gorge Almaty",
  "indystrialandyry": "Industrialization",
  "jyldan_keiin": "After 1941, due to the mass evacuation of factories and workers from the European part of the USSR during the Great Patriotic War, industry turned from an underdeveloped city into one of the largest industrial centers of the Soviet Union. Only in 1941-1945 the industrial potential of the city grew several times.",
  "qazirgi_zaman": "Present time",
  "qazirgi_yaqytta_almaty": "Currently, Almaty is the scientific, cultural, industrial and financial center of the country. The National Bank of the Republic of Kazakhstan is located in Almaty, as well as a number of embassies.",
  "usynystar": "Recommendations",
  "sizdin_bazanyz_bos": "Your database is empty",
  "birdene_durys_bolmady": "Something went wrong",
  "atayy": "Title",
  "bagasy": "Price",
  "meken_jaiy": "Address",
  "sipattama": "Description",
  "bailanys": "Contact",
  "tyrlar": "Tours",
  "tyrdyn_atayy": "Tour name",
  "ornalasqan_jeri": "Location",
  "totenshe_jagdailar_qyzmeti": "Emergency Service",
  "qonaq_uiler": "Hotels",
  "qonaq_ui_atayy": "Name of the hotel",
  "almatydagy_konsyldyq": "Consulate in Almaty",
  "azirbaijan_el": "Embassy of Azerbaijan",
  "satbaev_29": "Satpayeva 29/6",
  "ayganstan_el": "Embassy of Afghanistan",
  "miras_sha": "Miras microdistrict, 5",
  "armenia_el": "Embassy of Armenia",
  "seifyllin_dangyly": "498 Seifullina Ave.",
  "avstralia_el": "Embassy of Australia",
  "al_farabi_dangyly_77": "77/7 Al-Farabi Avenue",
  "belgia_el": "Embassy of Belgium",
  "dostyq_dangyly_138": "​138 Dostyk Avenue",
  "qytai_el": "Chinese Embassy",
  "baitasov_12": "Baitasov 12",
  "estonia_el": "Embassy of Estonia",
  "al_farabi_dangyly_120": "120/52 Al-Farabi Avenue",
  "fransia_el": "Embassy of France",
  "qonaev_77": "Kunaev, 77",
  "germania_el": "German Embassy",
  "ivanilova_2": "Ivanilova, 2",
  "vengria_el": "Embassy of Hungary",
  "musabaeva_4": "Musabayeva, 4",
  "undistan_el": "Embassy of India",
  "jarokova_362": "Zharokova, 362",
  "iran_el": "Embassy of Iran",
  "radlova_5a": "Radlova, 5a",
  "italia_el": "Italian Embassy",
  "dostyq_dangyly_38": "38 Dostyk Avenue",
  "qyrgyzstan_el": "Embassy of Kyrgyzstan",
  "lyganskii_koshesi_30a": "Luganskogo str., 30a",
  "mongolia_el": "Embassy of Mongolia",
  "musabaev_1": "Musabaev, 1",
  "polsha_el": "Embassy of Poland",
  "jarkent_9": "Zharkent, 9",
  "resei_el": "Russian Embassy",
  "jandosov_4": "Zhandosov 4",
  "ontustik_koreia_el": "Embassy of South Korea",
  "qaldaiaqov_66": "Kaldayakov, 66",
  "tajikstan_el": "Embassy of Tajikistan",
  "sanatorii_16": "Sanatorium, 16",
  "turkia_el": "Turkish Embassy",
  "tole_bi_29a": "Tole bi, 29a",
  "amerika_qurama_shtattary": "U.S. Embassy",
  "samal_shagynaydany_97": "Samal microdistrict - 2, 97",
  "ozbekstan_el": "Embassy of Uzbekistan",
  "jarokov_360": "Zharokov, 360",
  "salem": "Greetings to you,",
  "paidalanyshy": "user",
  "juieden_shygy": "Log out of the system",
  "orys_tili": "Ru language",
  "agylshyn_tili": "En language",
  "qazaq_tili": "Qaz language"
};
static const Map<String,dynamic> kk = {
  "saiahatynyzdy_tek_bizben_birge_zertteniz": "Saıahatyńyzdy tek bizben birge zertteńiz",
  "sizdin_atynyz": "Sizdiń atyńyz",
  "email": "Email",
  "password": "Password",
  "qupia_sozdi_rastanyz": "Qupıa sózdi rastańyz",
  "rastay": "Rastaý",
  "barlyq_oristerdi_toltyry_qajet": "Barlyq óristerdi toltyrý qajet",
  "qupia_sozder_birdei_emes": "Qupıa sózder birdeı emes",
  "google_account": "Google account",
  "sizde_eseptik_jazba_bar_ma_munda_juiege_kiriniz": "Sizde eseptik jazba bar ma? Munda júıege kirińiz",
  "qupia_sozdi_umyttynyz_ba": "Qupıa sózdi umyttyńyz ba?",
  "durys_elektrondyq_poshta_mekenjaiyn_engiziniz": "Durys elektrondyq poshta mekenjaıyn engizińiz",
  "elektrondyq_poshta_mekenjaiynyzga_elektrondyq_hat_jiberildi": "Elektrondyq poshta mekenjaıyńyzǵa elektrondyq hat jiberildi",
  "elektrondyq_poshta": "Elektrondyq poshta",
  "qazir_qalpyna_keltiriniz": "Qazir qalpyna keltirińiz",
  "aya_raiy_boljamy": "Aya raiy \nboljamy",
  "ornalasqan_jeriniz": "Ornalasqan \njerińiz",
  "jarnama": "Jarnama",
  "qala_tarihy": "Qala tarıhy",
  "qazirgi_almaty_aymagynda_arheologtar": "Qazirgi Almaty aýmaǵynda arheologtar tapqan ejelgi eskertkishterge súıene otyryp, bul aımaqty ejelden kóshpeli jáne jartylaı otyryqshy taıpalar mekendegen dep aıtýǵa bolady. Bizdiń dáýirimizge deıingi VI—III ǵasyrlardaǵy saqtardyń eń erekshe eskertkishteri bolyp tabylady.",
  "orta_gasyrlar": "Orta ǵasyrlar",
  "vernyi": "Vernyı",
  "kenes_kezeni": "Keńes kezeńi",
  "vernyi_qazirgi_almaty": "Vernyı (qazirgi Almaty) — 1854 jyly 4 aqpanda (16 aqpanda) Reseı úkimeti qurǵan qala, áskerı bekinis. Kóp uzamaı ol ósip, Reseıdiń ortalyq aımaqtarynan (Voronej, Orel, Kýrsk gýbernıalary) qonystanýshylar belsendi kelgen iri kazak stansıasyna aınaldy. 1867 jyly Vernyı Jetisý oblysynyń ortalyǵyna aınaldy.",
  "jyly_vernyida": "1918 jyly Vernyıda Keńes ókimeti ornady. Oblyspen qala RSFSR quramyndaǵy Túrkistan avtonomıasynyń quramyna kirdi. 1921 jyly 5 aqpanda Vernyıdy Almaty shatqalynyń eski ataýy boıynsha Almaty dep ózgertý týraly sheshim qabyldandy",
  "indystrialandyry": "Indýstrıalandyrý",
  "jyldan_keiin": "1941 jyldan keıin, Uly Otan soǵysy kezinde KSRO-nyń eýropalyq bóliginen zaýyttar men jumysshylardyń jappaı evakýasıalanýyna baılanysty, ónerkásip damymaǵan qaladan Almaty Keńes Odaǵynyń iri ónerkásiptik ortalyqtarynyń birine aınaldy. Tek 1941-1945 jyldary qalanyń ónerkásiptik áleýeti birneshe ese ósti.",
  "qazirgi_zaman": "Qazirgi zaman",
  "qazirgi_yaqytta_almaty": "Qazirgi ýaqytta Almaty-eldiń ǵylymı, mádenı, ónerkásiptik jáne qarjy ortalyǵy. Almatyda Qazaqstan Respýblıkasynyń Ulttyq Banki, sondaı-aq birqatar elshilikter ornalasqan.",
  "usynystar": "Usynystar",
  "sizdin_bazanyz_bos": "Sizdiń bazańyz bos",
  "birdene_durys_bolmady": "Birdeńe durys bolmady",
  "atayy": "Ataýy",
  "bagasy": "Baǵasy",
  "meken_jaiy": "Meken-jaıy",
  "sipattama": "Sıpattama",
  "bailanys": "Baılanys",
  "tyrlar": "Týrlar",
  "tyrdyn_atayy": "Týrdyń ataýy",
  "ornalasqan_jeri": "Ornalasqan jeri",
  "totenshe_jagdailar_qyzmeti": "Tótenshe jaǵdaılar qyzmeti",
  "qonaq_uiler": "Qonaq úıler",
  "qonaq_ui_atayy": "Qonaq úı ataýy",
  "almatydagy_konsyldyq": "Almatydaǵy konsýldyq",
  "azirbaijan_el": "Ázirbaıjan Elshiligi",
  "satbaev_29": "Sátbaev 29/6",
  "ayganstan_el": "Aýǵanstan Elshiligi",
  "miras_sha": "Mıras Shaǵynaýdany, 5",
  "armenia_el": "Armenıa Elshiligi",
  "seifyllin_dangyly": "Seıfýllın Dańǵyly, 498",
  "avstralia_el": "Avstralıa Elshiligi",
  "al_farabi_dangyly_77": "Ál-Farabı Dańǵyly, 77/7",
  "belgia_el": "Belgıa Elshiligi",
  "dostyq_dangyly_138": "​Dostyq Dańǵyly, 138",
  "qytai_el": "Qytaı Elshiligi",
  "baitasov_12": "Baıtasov, 12",
  "estonia_el": "Estonıa Elshiligi",
  "al_farabi_dangyly_120": "Ál-Farabı Dańǵyly, 120/52",
  "fransia_el": "Fransıa Elshiligi",
  "qonaev_77": "Qonaev, 77",
  "germania_el": "Germanıa Elshiligi",
  "ivanilova_2": "Ivanılova, 2",
  "vengria_el": "Vengrıa Elshiligi",
  "musabaeva_4": "Musabaeva, 4",
  "undistan_el": "Úndistan Elshiligi",
  "jarokova_362": "Jarokova, 362",
  "iran_el": "Iran Elshiligi",
  "radlova_5a": "Radlova, 5a",
  "italia_el": "Italıa Elshiligi",
  "dostyq_dangyly_38": "Dostyq Dańǵyly, 38",
  "qyrgyzstan_el": "Qyrǵyzstan Elshiligi",
  "lyganskii_koshesi_30a": "Lýganskıı kóshesi, 30a",
  "mongolia_el": "Mońǵolıa Elshiligi",
  "musabaev_1": "Musabaev, 1",
  "polsha_el": "Polsha Elshiligi",
  "jarkent_9": "Jarkent, 9",
  "resei_el": "Reseı Elshiligi",
  "jandosov_4": "Jandosov 4",
  "ontustik_koreia_el": "Ońtústik Koreıa Elshiligi",
  "qaldaiaqov_66": "Qaldaıaqov, 66",
  "tajikstan_el": "Tájikstan Elshiligi",
  "sanatorii_16": "Sanatorıı, 16",
  "turkia_el": "Túrkıa Elshiligi",
  "tole_bi_29a": "Tóle bı, 29a",
  "amerika_qurama_shtattary": "Amerıka Qurama Shtattary Elshiligi",
  "samal_shagynaydany_97": "Samal-2 shaǵynaýdany, 97",
  "ozbekstan_el": "Ózbekstan Elshiligi",
  "jarokov_360": "Jarokov, 360",
  "salem": "Salem, ",
  "paidalanyshy": "paidalanyshy",
  "juieden_shygy": "Júıeden shyǵý",
  "orys_tili": "Orys tili",
  "agylshyn_tili": "Aǵylshyn tili",
  "qazaq_tili": "Qazaq tili"
};
static const Map<String,dynamic> ru = {
  "saiahatynyzdy_tek_bizben_birge_zertteniz": "Исследуйте свое путешествие только с нами",
  "sizdin_atynyz": "Ваше имя",
  "email": "Email",
  "password": "Password",
  "qupia_sozdi_rastanyz": "Подтвердите пароль",
  "rastay": "Подтверждение",
  "barlyq_oristerdi_toltyry_qajet": "Необходимо заполнить все поля",
  "qupia_sozder_birdei_emes": "Пароли не совпадают",
  "google_account": "Google account",
  "sizde_eseptik_jazba_bar_ma_munda_juiege_kiriniz": "У вас есть учетная запись? Войдите здесь",
  "qupia_sozdi_umyttynyz_ba": "Забыли пароль?",
  "durys_elektrondyq_poshta_mekenjaiyn_engiziniz": "Введите правильный адрес электронной почты",
  "elektrondyq_poshta_mekenjaiynyzga_elektrondyq_hat_jiberildi": "Электронное письмо отправлено на ваш адрес электронной почты",
  "elektrondyq_poshta": "Электронная почта",
  "qazir_qalpyna_keltiriniz": "Восстановить сейчас",
  "aya_raiy_boljamy": "Прогноз \nпогоды",
  "ornalasqan_jeriniz": "Ваше \nместоположение",
  "jarnama": "Реклама",
  "qala_tarihy": "История города",
  "qazirgi_almaty_aymagynda_arheologtar": "Основываясь на древних памятниках, найденных археологами на территории современного Алматы, можно сказать, что этот район издавна населяли кочевые и полуоседлые племена. Самыми необычными памятниками саков являются ВІ—III вв. до н. э.",
  "orta_gasyrlar": "Средневековье",
  "vernyi": "Верный",
  "kenes_kezeni": "Советский период",
  "vernyi_qazirgi_almaty": "Верный (ныне Almaty) - город, военная крепость, созданная Правительством России 4 февраля (16 февраля) 1854 года. Вскоре он вырос и превратился в крупную казачью станцию, куда активно приезжали поселенцы из центральных регионов России (Воронежская, Орловская, Курская губернии). В 1867 году Верный стал центром Жетысуской области.",
  "jyly_vernyida": "В 1918 году в верном была установлена советская власть. С областью город вошел в состав Туркестанской автономии в составе РСФСР. 5 февраля 1921 года было принято решение переименовать Верный в Алмату по старому названию ущелья Almaty",
  "indystrialandyry": "Индустриализация",
  "jyldan_keiin": "После 1941 года, в связи с массовой эвакуацией заводов и рабочих из европейской части СССР во время Великой Отечественной войны, промышленность превратилась из слаборазвитого города в один из крупнейших промышленных центров Советского Союза. Только в 1941-1945 годах промышленный потенциал города вырос в несколько раз.",
  "qazirgi_zaman": "Настоящее время",
  "qazirgi_yaqytta_almaty": "В настоящее время Алматы - научный, культурный, промышленный и финансовый центр страны. В Алматы находится Национальный банк Республики Казахстан, а также ряд посольств.",
  "usynystar": "Рекомендации",
  "sizdin_bazanyz_bos": "Ваша база пуста",
  "birdene_durys_bolmady": "Что-то пошло не так",
  "atayy": "Название",
  "bagasy": "Цена",
  "meken_jaiy": "Адрес",
  "sipattama": "Описание",
  "bailanys": "Контакты",
  "tyrlar": "Туры",
  "tyrdyn_atayy": "Название тура",
  "ornalasqan_jeri": "Расположение",
  "totenshe_jagdailar_qyzmeti": "Аварийная служба",
  "qonaq_uiler": "Отели",
  "qonaq_ui_atayy": "Название отеля",
  "almatydagy_konsyldyq": "Консульство в Алматы",
  "azirbaijan_el": "Посольство Азербайджана",
  "satbaev_29": "Сатпаев 29/6",
  "ayganstan_el": "Посольство Афганистана",
  "miras_sha": "Микрорайон Мирас, 5",
  "armenia_el": "Посольство Армении",
  "seifyllin_dangyly": "Пр. Сейфуллина, 498",
  "avstralia_el": "Посольство Австралии",
  "al_farabi_dangyly_77": "Проспект Аль-Фараби, 77/7",
  "belgia_el": "Посольство Белгии",
  "dostyq_dangyly_138": "​Проспект Достык, 138",
  "qytai_el": "Посольство Китая",
  "baitasov_12": "Байтасов, 12",
  "estonia_el": "Посольство Эстонии",
  "al_farabi_dangyly_120": "Проспект Аль-Фараби, 120/52",
  "fransia_el": "Посольство Франции",
  "qonaev_77": "Кунаев, 77",
  "germania_el": "Посольство Германии",
  "ivanilova_2": "Иванилова, 2",
  "vengria_el": "Посольство Венгрии",
  "musabaeva_4": "Мусабаева, 4",
  "undistan_el": "Посольство Индии",
  "jarokova_362": "Жарокова, 362",
  "iran_el": "Посольство Ирана",
  "radlova_5a": "Радлова, 5а",
  "italia_el": "Посольство Италии",
  "dostyq_dangyly_38": "Проспект Достык, 38",
  "qyrgyzstan_el": "Посольство Кыргызстана",
  "lyganskii_koshesi_30a": "Ул. Луганского, 30а",
  "mongolia_el": "Посольство Монголии",
  "musabaev_1": "Мусабаев, 1",
  "polsha_el": "Посольство Польши",
  "jarkent_9": "Жаркент, 9",
  "resei_el": "Посольство России",
  "jandosov_4": "Жандосов 4",
  "ontustik_koreia_el": "Посольство Южной Кореи",
  "qaldaiaqov_66": "Калдаяков, 66",
  "tajikstan_el": "Посольство Таджикистана",
  "sanatorii_16": "Санаторий, 16",
  "turkia_el": "Посольство Турции",
  "tole_bi_29a": "Толе би, 29а",
  "amerika_qurama_shtattary": "Посольство США",
  "samal_shagynaydany_97": "Микрорайон Самал - 2, 97",
  "ozbekstan_el": "Посольство Узбекистана",
  "jarokov_360": "Жароков, 360",
  "salem": "Приветствую вас, ",
  "paidalanyshy": "пользователь",
  "juieden_shygy": "Выход из системы",
  "orys_tili": "Русский язык",
  "agylshyn_tili": "Английский язык",
  "qazaq_tili": "Казахский язык"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"en": en, "kk": kk, "ru": ru};
}
